### ISSUE TITLE
In-place edit does not work

### ISSUE THREAD

**Issue by stefan-h-singer** [iRessources/AgileDwarf#12]
NoMethodError (undefined method `flatten!' for {"estimated_hours"=>"2"}:Hash):
  plugins/AgileDwarf/app/controllers/adtaskinl_controller.rb:74:in`inplace'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in`block in process_action'

**Comment by markablov** [comment]
Fixed by d121ab82e815cf382e1ca4061556d88982d1fdfd

**Comment by DuncanHills** [comment]
Having the same issue, not fixed by commit. When attempting to add start/end dates:

```
Started POST "/adsprintinl/inplace" for <MY_IP_HERE> at 2012-08-11 16:45:15 -0400
Processing by AdsprintinlController#inplace as HTML
  Parameters: {"ir_start_date"=>"08/06/2012", "element_id"=>"", "id"=>"2", "project_id"=>"1", "authenticity_token"=>"MY_AUTH_TOKEN_HERE"}
Completed 500 Internal Server Error in 7ms

NoMethodError (undefined method `flatten!' for {"ir_start_date"=>"08/06/2012"}:Hash):
  plugins/AgileDwarf/app/controllers/adsprintinl_controller.rb:27:in `inplace'
...
```

When editing issue name:

```
Started POST "/adtaskinl/inplace" for <MY_IP_HERE> at 2012-08-11 16:52:34 -0400
Processing by AdtaskinlController#inplace as HTML
  Parameters: {"subject"=>"Issue Name", "element_id"=>"", "id"=>"1", "project_id"=>"1", "authenticity_token"=>"MY_AUTH_TOKEN"}
Completed 500 Internal Server Error in 9ms

NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/AgileDwarf/app/controllers/adtaskinl_controller.rb:73:in `inplace'
...
```

**Comment by stefan-h-singer** [comment]
Yeah, still same issue here.

**Comment by lfagundes** [comment]
Same issue here. I applied the patch from pull request, but error remains. This happened when I tried to change the task %done with slider in "Tasks" tab.

Started POST "/adtaskinl/inplace" for XXX.XXX.XXX at 2012-08-14 09:43:42 -0300
Processing by AdtaskinlController#inplace as _/_
  Parameters: {"id"=>"59", "done_ratio"=>"30", "project_id"=>"12", "authenticity_token"=>"UNDISCLOSED="}
Completed 500 Internal Server Error in 8ms

NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/AgileDwarf/app/controllers/adtaskinl_controller.rb:73:in`inplace'
  actionpack (3.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.3) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.3) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.3) lib/active_support/callbacks.rb:469:in `_run__2918539924987108546__process_action__4273326762448754092__callbacks'
  activesupport (3.2.3) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.3) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.3) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.3) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.3) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.3) lib/action_controller/metal/params_wrapper.rb:205:in`process_action'
  activerecord (3.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.3) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.3) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.3) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.3) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.3) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.3) lib/journey/router.rb:68:in`block in call'
  journey (1.0.3) lib/journey/router.rb:56:in `each'
  journey (1.0.3) lib/journey/router.rb:56:in`call'
  actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:600:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in`call'
  actionpack (3.2.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in`call'
  rack (1.4.1) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.3) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.3) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
  actionpack (3.2.3) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.3) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `call'
  actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `_run__3354388585629346805__call__3267009547456176619__callbacks'
  activesupport (3.2.3) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.3) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.3) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.3) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.3) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.3) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.3) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.3) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.3) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in`pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.3) lib/rails/engine.rb:479:in`call'
  railties (3.2.3) lib/rails/application.rb:220:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in`call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in `service'

**Comment by markablov** [comment]
Redmine version?

**Comment by DuncanHills** [comment]
Environment:
Redmine version 2.0.3.stable
Ruby version 1.9.3 (i686-linux)
Rails version 3.2.6
Environment production
Database adapter Mysql2
Redmine plugins:
AgileDwarf 0.0.3

**Comment by markablov** [comment]
please, check 4d14649f770d6b3eef44e595c678484e435c51a5

**Comment by lfagundes** [comment]
I couldn't test properly because commit  832dee (issue #16 about urls) broke the interface. I checked 5e201, before that, and applied a patch containing just 4d146. It's better but still not fixed. In "Tasks" interface I tried:
- Adding hours - OK now (it wasn't before)
- Sliding the % complete - NO, got 400 bad request in server
- Editing task name - NO, nothing happens, doesn't hit the server

For me the % complete is the most critical, as now I can't modify it with the normal update (I don't know if this is a consequence of AgileDwarf or not, but it's now disabled)

My environment:

Environment:
  Redmine version                          2.0.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.3
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  AgileDwarf                               0.0.3
  redmine_code_review                      0.5.0
  redmine_plugin_views_revisions           0.0.1
  redmine_smart_issues_sort                0.3.1

**Comment by lfagundes** [comment]
Another thing I notice in this page is that when it loads, I get 2 javascript errors:

element.dispatchEvent is not a function
element.attachEvent is not a functionelement.attachEvent is not a function

Happens inside prototype.js. For the second message, the stack trace begins in application.js line 481, the first one couldn't be traced from outside prototype.js.

**Comment by GreenRover** [comment]
I have also problems with in-place edit
I use atest edition of agiledwarf, last commit 4d14649f770d6b3eef44e595c678484e435c51a 

```
HTTP POST http://10.0.0.144/redmine/adtaskinl/inplace
authenticity_token  xdAJs*****9R/o=
element_id  
estimated_hours 2
id  1489
project_id  5
```

I get:  Redmine 500 error

I the ./log/production.log i find

```
Started POST "/redmine/adtaskinl/inplace" for 10.0.0.200 at 2012-08-15 14:01:00 +0200
Processing by AdtaskinlController#inplace as HTML
  Parameters: {"estimated_hours"=>"2", "element_id"=>"", "id"=>"1489", "project_id"=>"5", "authenticity_token"=>"xdAJszLOC2cekyC4eS/MBc4QD6gvMkV+AZfyB7/9R/o="}
Completed 500 Internal Server Error in 12m
NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/AgileDwarf/app/controllers/adtaskinl_controller.rb:73:in `inplace'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:469:in `_run__74897556__process_action__30447061__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in `dispatch'
  ......
  <internal:prelude>:10:in `synchronize'
  passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.15) helper-scripts/passenger-spawn-server:99:in `<main>'
```

Ruby: 1.9.2
Gem: 1.8.11
Rails 3.2.6
Redmine 2.0  from http://redmine.rubyforge.org/svn/branches/2.0-stable

**Comment by stefan-h-singer** [comment]
I think this can be closed now thanks to 6a2d87edbe7aff5df4eada61a6dde99a74a37663 ? Everything seems to be working fine here now.
